function strf = getSTRF(param)
%%
% Get the STRFs of the first 3 layer
% Steps:
% 1. For each S1 unit, its STRF is difined as the corresponding basis.
% 2. For each Sn (n>1) unit, its STRF is obtained by linearly combining the
%    STRFs of the units in previous layers.
%
% input:
%   param: The parameters for the SHMAX model, generated by setParameters.m
% output:
%   strf: a 1*3 cell, the STRF of the first S layers


base = 0;
load(['S1Result', filesep, 'base_', num2str(param.Bn(1)), '_', num2str(param.Sn(1)), '_', num2str(param.Bs(1)), '.mat'], 'base');
strf{1} = reshape(base, [param.Bs(1), param.Bs(1), param.Bn(1)]);
s = param.Bs(1) + param.Bs(1) * param.s1(1);
strf{2} = zeros(s, s, param.Bn(2));
s = s + param.Bs(1) * prod(param.s1(1:2));
strf{3} = zeros(s, s, param.Bn(3));

for l = 2:3
    load(['S', num2str(l), 'Result', filesep, 'base_', num2str(param.Bn(l)), '_', num2str(param.Sn(l)), '_', num2str(param.Bs(l)), '.mat'], 'base');
    base = reshape(base, [param.Bs(l), param.Bs(l), param.Bn(l-1), param.Bn(l)]);
    for i = 1:param.Bn(l)
        for j = 1:param.Bn(l-1)
            baseEx = kron(base(:, :, j, i), ones(prod(param.s1(1:l-1))));
            baseEx(end+1, :) = 0;
            baseEx(:, end+1) = 0;
            strf{l}(:, :, i) = strf{l}(:, :, i) + conv2(baseEx, strf{l-1}(:, :, j), 'full');
        end
    end
end
